# Generated by Django 2.0.3 on 2020-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
